### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by jsalexjs** [kinoute/Hack-Z370-HD3P-i5-8400#3]
Hey have you managed to get sound working natively on your config? Thanks :)

**Comment by kinoute** [comment]
Hi,

Yes, sound should work OOTB with my EFI folder and this motherboard.

**Comment by bigbigbigfish** [comment]
The same to me ,no sound.
and my hardware also GA z370 + i5 8400

**Comment by kinoute** [comment]
@bigbigbigfish Try to change the `alcid` Clover boot option in the config.plist file to 1. (it is set to 27 at the moment).

I just tested my headphones + microphone (two separate cables) it works with the following settings:

* alcid set to 1 instead of 27 ;
* my microphone plugged to the pink input on the back of the motherboard ;
* the headphones plugged to the input next to the pink output (the middle one)

on macOS / Preferences / Sound, I set output to "built-in speakers" and the input to "built-in microphone".

I will update the config.plist ASAP.

**Comment by bigbigbigfish** [comment]
Thanks kinoute.

I just change alcid to 7  to solve it.

The EFI almost perfect, but when system booting the screen will flash  with Graphics 630 card.

**Comment by kinoute** [comment]
@bigbigbigfish If you're talking about the visual glitch you get at booting (at the loading bar), this is a known issue on many hackintoshes since 10.14.x and this is not important

**Comment by kinoute** [comment]
I updated the instructions in the README regarding sound:

https://github.com/kinoute/Hack-Z370-HD3P-i5-8400#Sound
